/**
 * Apex Protocol — Exercise Library
 *
 * Structured catalog of exercises across all major categories.
 * Used by the database seed and program generator.
 *
 * Fields:
 *  name            — unique exercise name
 *  category        — legacy: compound | isolation | cardio
 *  muscleGroup     — legacy: primary muscle group label
 *  equipment       — barbell | dumbbell | cable | machine | kettlebell | band | bodyweight | cardio_machine | mixed | none
 *  bodyPart        — Lower Body | Upper Body | Core | Full Body | Cardio | Mobility
 *  primaryMuscle   — specific primary muscle
 *  secondaryMuscles — array of secondary muscles
 *  movementPattern — squat | hinge | lunge_single_leg | horizontal_push | vertical_push |
 *                    horizontal_pull | vertical_pull | rotation | anti_rotation | carry |
 *                    cardio | mobility | balance
 *  exerciseType    — compound | isolation | cardio | plyometric | core | mobility | rehab
 *  goalTags        — strength | hypertrophy | fat_loss | endurance | athletic_performance |
 *                    general_fitness | mobility_recovery
 *  difficulty      — beginner | intermediate | advanced
 *  isCompound      — true if multi-joint movement
 *  isUnilateral    — true if single-limb movement
 */

export interface ExerciseDefinition {
  name: string;
  category: string;
  muscleGroup: string | null;
  equipment: string | null;
  bodyPart?: string;
  primaryMuscle?: string;
  secondaryMuscles?: string[];
  movementPattern?: string;
  exerciseType?: string;
  goalTags?: string[];
  difficulty?: string;
  isCompound?: boolean;
  isUnilateral?: boolean;
  instructions?: string;
}

// ─── A. LOWER BODY — SQUAT / KNEE-DOMINANT ────────────────────────────────────

const SQUAT_EXERCISES: ExerciseDefinition[] = [
  {
    name: 'Back Squat',
    category: 'compound', muscleGroup: 'Quads', equipment: 'barbell',
    bodyPart: 'Lower Body', primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Hamstrings', 'Erector Spinae', 'Core'],
    movementPattern: 'squat', exerciseType: 'compound',
    goalTags: ['strength', 'hypertrophy', 'athletic_performance'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Front Squat',
    category: 'compound', muscleGroup: 'Quads', equipment: 'barbell',
    bodyPart: 'Lower Body', primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Core', 'Upper Back'],
    movementPattern: 'squat', exerciseType: 'compound',
    goalTags: ['strength', 'hypertrophy', 'athletic_performance'],
    difficulty: 'advanced', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Goblet Squat',
    category: 'compound', muscleGroup: 'Quads', equipment: 'dumbbell',
    bodyPart: 'Lower Body', primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Core'],
    movementPattern: 'squat', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'general_fitness'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Safety Bar Squat',
    category: 'compound', muscleGroup: 'Quads', equipment: 'barbell',
    bodyPart: 'Lower Body', primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Hamstrings', 'Core'],
    movementPattern: 'squat', exerciseType: 'compound',
    goalTags: ['strength', 'hypertrophy'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Zercher Squat',
    category: 'compound', muscleGroup: 'Quads', equipment: 'barbell',
    bodyPart: 'Lower Body', primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Core', 'Biceps'],
    movementPattern: 'squat', exerciseType: 'compound',
    goalTags: ['strength', 'athletic_performance'],
    difficulty: 'advanced', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Hack Squat',
    category: 'compound', muscleGroup: 'Quads', equipment: 'machine',
    bodyPart: 'Lower Body', primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Hamstrings'],
    movementPattern: 'squat', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'general_fitness'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Smith Machine Squat',
    category: 'compound', muscleGroup: 'Quads', equipment: 'machine',
    bodyPart: 'Lower Body', primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Hamstrings'],
    movementPattern: 'squat', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'general_fitness'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Leg Press',
    category: 'compound', muscleGroup: 'Quads', equipment: 'machine',
    bodyPart: 'Lower Body', primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Hamstrings'],
    movementPattern: 'squat', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'general_fitness'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Belt Squat',
    category: 'compound', muscleGroup: 'Quads', equipment: 'machine',
    bodyPart: 'Lower Body', primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Hamstrings'],
    movementPattern: 'squat', exerciseType: 'compound',
    goalTags: ['strength', 'hypertrophy'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Split Squat',
    category: 'compound', muscleGroup: 'Quads', equipment: 'bodyweight',
    bodyPart: 'Lower Body', primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Hamstrings'],
    movementPattern: 'lunge_single_leg', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'general_fitness'],
    difficulty: 'beginner', isCompound: true, isUnilateral: true,
  },
  {
    name: 'Bulgarian Split Squat',
    category: 'compound', muscleGroup: 'Quads', equipment: 'dumbbell',
    bodyPart: 'Lower Body', primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Hamstrings', 'Core'],
    movementPattern: 'lunge_single_leg', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'strength', 'athletic_performance'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: true,
  },
  {
    name: 'Step-Up',
    category: 'compound', muscleGroup: 'Quads', equipment: 'dumbbell',
    bodyPart: 'Lower Body', primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Hamstrings'],
    movementPattern: 'lunge_single_leg', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'athletic_performance', 'general_fitness'],
    difficulty: 'beginner', isCompound: true, isUnilateral: true,
  },
  {
    name: 'Walking Lunge',
    category: 'compound', muscleGroup: 'Quads', equipment: 'dumbbell',
    bodyPart: 'Lower Body', primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Hamstrings', 'Core'],
    movementPattern: 'lunge_single_leg', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'fat_loss', 'athletic_performance'],
    difficulty: 'beginner', isCompound: true, isUnilateral: true,
  },
  {
    name: 'Reverse Lunge',
    category: 'compound', muscleGroup: 'Quads', equipment: 'dumbbell',
    bodyPart: 'Lower Body', primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Hamstrings'],
    movementPattern: 'lunge_single_leg', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'general_fitness'],
    difficulty: 'beginner', isCompound: true, isUnilateral: true,
  },
  {
    name: 'Curtsy Lunge',
    category: 'compound', muscleGroup: 'Glutes', equipment: 'dumbbell',
    bodyPart: 'Lower Body', primaryMuscle: 'Glutes',
    secondaryMuscles: ['Quadriceps', 'Abductors'],
    movementPattern: 'lunge_single_leg', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'general_fitness'],
    difficulty: 'beginner', isCompound: true, isUnilateral: true,
  },
  {
    name: 'Sissy Squat',
    category: 'isolation', muscleGroup: 'Quads', equipment: 'bodyweight',
    bodyPart: 'Lower Body', primaryMuscle: 'Quadriceps',
    secondaryMuscles: [],
    movementPattern: 'squat', exerciseType: 'isolation',
    goalTags: ['hypertrophy'],
    difficulty: 'intermediate', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Leg Extension',
    category: 'isolation', muscleGroup: 'Quads', equipment: 'machine',
    bodyPart: 'Lower Body', primaryMuscle: 'Quadriceps',
    secondaryMuscles: [],
    movementPattern: 'squat', exerciseType: 'isolation',
    goalTags: ['hypertrophy', 'general_fitness'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Wall Sit',
    category: 'isolation', muscleGroup: 'Quads', equipment: 'bodyweight',
    bodyPart: 'Lower Body', primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes'],
    movementPattern: 'squat', exerciseType: 'isolation',
    goalTags: ['endurance', 'general_fitness'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Pistol Squat',
    category: 'compound', muscleGroup: 'Quads', equipment: 'bodyweight',
    bodyPart: 'Lower Body', primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Core'],
    movementPattern: 'squat', exerciseType: 'compound',
    goalTags: ['strength', 'athletic_performance'],
    difficulty: 'advanced', isCompound: true, isUnilateral: true,
  },
  {
    name: 'Box Squat',
    category: 'compound', muscleGroup: 'Quads', equipment: 'barbell',
    bodyPart: 'Lower Body', primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Hamstrings'],
    movementPattern: 'squat', exerciseType: 'compound',
    goalTags: ['strength', 'athletic_performance'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
];

// ─── B. LOWER BODY — HINGE / HIP-DOMINANT ─────────────────────────────────────

const HINGE_EXERCISES: ExerciseDefinition[] = [
  {
    name: 'Deadlift',
    category: 'compound', muscleGroup: 'Full Body', equipment: 'barbell',
    bodyPart: 'Full Body', primaryMuscle: 'Hamstrings',
    secondaryMuscles: ['Glutes', 'Erector Spinae', 'Trapezius', 'Forearms', 'Core'],
    movementPattern: 'hinge', exerciseType: 'compound',
    goalTags: ['strength', 'hypertrophy', 'athletic_performance'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Sumo Deadlift',
    category: 'compound', muscleGroup: 'Full Body', equipment: 'barbell',
    bodyPart: 'Lower Body', primaryMuscle: 'Hamstrings',
    secondaryMuscles: ['Glutes', 'Adductors', 'Erector Spinae'],
    movementPattern: 'hinge', exerciseType: 'compound',
    goalTags: ['strength', 'hypertrophy'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Romanian Deadlift',
    category: 'compound', muscleGroup: 'Hamstrings', equipment: 'barbell',
    bodyPart: 'Lower Body', primaryMuscle: 'Hamstrings',
    secondaryMuscles: ['Glutes', 'Erector Spinae', 'Core'],
    movementPattern: 'hinge', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'strength'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Stiff-Leg Deadlift',
    category: 'compound', muscleGroup: 'Hamstrings', equipment: 'barbell',
    bodyPart: 'Lower Body', primaryMuscle: 'Hamstrings',
    secondaryMuscles: ['Glutes', 'Erector Spinae'],
    movementPattern: 'hinge', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'strength'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Trap Bar Deadlift',
    category: 'compound', muscleGroup: 'Full Body', equipment: 'barbell',
    bodyPart: 'Full Body', primaryMuscle: 'Hamstrings',
    secondaryMuscles: ['Quadriceps', 'Glutes', 'Erector Spinae', 'Trapezius'],
    movementPattern: 'hinge', exerciseType: 'compound',
    goalTags: ['strength', 'athletic_performance'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Rack Pull',
    category: 'compound', muscleGroup: 'Back', equipment: 'barbell',
    bodyPart: 'Full Body', primaryMuscle: 'Erector Spinae',
    secondaryMuscles: ['Trapezius', 'Glutes', 'Hamstrings'],
    movementPattern: 'hinge', exerciseType: 'compound',
    goalTags: ['strength'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Good Morning',
    category: 'compound', muscleGroup: 'Hamstrings', equipment: 'barbell',
    bodyPart: 'Lower Body', primaryMuscle: 'Hamstrings',
    secondaryMuscles: ['Glutes', 'Erector Spinae'],
    movementPattern: 'hinge', exerciseType: 'compound',
    goalTags: ['strength', 'hypertrophy'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Hip Thrust',
    category: 'compound', muscleGroup: 'Glutes', equipment: 'barbell',
    bodyPart: 'Lower Body', primaryMuscle: 'Glutes',
    secondaryMuscles: ['Hamstrings', 'Core'],
    movementPattern: 'hinge', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'strength'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Barbell Glute Bridge',
    category: 'compound', muscleGroup: 'Glutes', equipment: 'barbell',
    bodyPart: 'Lower Body', primaryMuscle: 'Glutes',
    secondaryMuscles: ['Hamstrings', 'Core'],
    movementPattern: 'hinge', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'general_fitness'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Cable Pull-Through',
    category: 'compound', muscleGroup: 'Glutes', equipment: 'cable',
    bodyPart: 'Lower Body', primaryMuscle: 'Glutes',
    secondaryMuscles: ['Hamstrings', 'Core'],
    movementPattern: 'hinge', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'general_fitness'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Kettlebell Swing',
    category: 'compound', muscleGroup: 'Glutes', equipment: 'kettlebell',
    bodyPart: 'Full Body', primaryMuscle: 'Glutes',
    secondaryMuscles: ['Hamstrings', 'Core', 'Shoulders'],
    movementPattern: 'hinge', exerciseType: 'compound',
    goalTags: ['athletic_performance', 'fat_loss', 'endurance'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Single-Leg Romanian Deadlift',
    category: 'compound', muscleGroup: 'Hamstrings', equipment: 'dumbbell',
    bodyPart: 'Lower Body', primaryMuscle: 'Hamstrings',
    secondaryMuscles: ['Glutes', 'Core'],
    movementPattern: 'hinge', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'athletic_performance'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: true,
  },
  {
    name: 'Back Extension',
    category: 'isolation', muscleGroup: 'Back', equipment: 'machine',
    bodyPart: 'Lower Body', primaryMuscle: 'Erector Spinae',
    secondaryMuscles: ['Glutes', 'Hamstrings'],
    movementPattern: 'hinge', exerciseType: 'isolation',
    goalTags: ['hypertrophy', 'general_fitness'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Reverse Hyper',
    category: 'isolation', muscleGroup: 'Glutes', equipment: 'machine',
    bodyPart: 'Lower Body', primaryMuscle: 'Glutes',
    secondaryMuscles: ['Hamstrings', 'Erector Spinae'],
    movementPattern: 'hinge', exerciseType: 'isolation',
    goalTags: ['hypertrophy', 'mobility_recovery'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Hamstring Curl',
    category: 'isolation', muscleGroup: 'Hamstrings', equipment: 'machine',
    bodyPart: 'Lower Body', primaryMuscle: 'Hamstrings',
    secondaryMuscles: [],
    movementPattern: 'hinge', exerciseType: 'isolation',
    goalTags: ['hypertrophy', 'general_fitness'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Nordic Curl',
    category: 'isolation', muscleGroup: 'Hamstrings', equipment: 'bodyweight',
    bodyPart: 'Lower Body', primaryMuscle: 'Hamstrings',
    secondaryMuscles: ['Glutes', 'Core'],
    movementPattern: 'hinge', exerciseType: 'isolation',
    goalTags: ['strength', 'athletic_performance'],
    difficulty: 'advanced', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Seated Ham Curl',
    category: 'isolation', muscleGroup: 'Hamstrings', equipment: 'machine',
    bodyPart: 'Lower Body', primaryMuscle: 'Hamstrings',
    secondaryMuscles: [],
    movementPattern: 'hinge', exerciseType: 'isolation',
    goalTags: ['hypertrophy', 'general_fitness'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Glute Ham Raise',
    category: 'compound', muscleGroup: 'Hamstrings', equipment: 'machine',
    bodyPart: 'Lower Body', primaryMuscle: 'Hamstrings',
    secondaryMuscles: ['Glutes', 'Core'],
    movementPattern: 'hinge', exerciseType: 'compound',
    goalTags: ['strength', 'hypertrophy'],
    difficulty: 'advanced', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Calf Raise',
    category: 'isolation', muscleGroup: 'Calves', equipment: 'machine',
    bodyPart: 'Lower Body', primaryMuscle: 'Gastrocnemius',
    secondaryMuscles: ['Soleus'],
    movementPattern: 'hinge', exerciseType: 'isolation',
    goalTags: ['hypertrophy', 'general_fitness'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
];

// ─── C. UPPER BODY — HORIZONTAL PUSH ──────────────────────────────────────────

const HORIZONTAL_PUSH_EXERCISES: ExerciseDefinition[] = [
  {
    name: 'Bench Press',
    category: 'compound', muscleGroup: 'Chest', equipment: 'barbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Pectoralis Major',
    secondaryMuscles: ['Triceps', 'Anterior Deltoid'],
    movementPattern: 'horizontal_push', exerciseType: 'compound',
    goalTags: ['strength', 'hypertrophy'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Dumbbell Bench Press',
    category: 'compound', muscleGroup: 'Chest', equipment: 'dumbbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Pectoralis Major',
    secondaryMuscles: ['Triceps', 'Anterior Deltoid'],
    movementPattern: 'horizontal_push', exerciseType: 'compound',
    goalTags: ['strength', 'hypertrophy'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Incline Barbell Bench Press',
    category: 'compound', muscleGroup: 'Chest', equipment: 'barbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Pectoralis Major (Upper)',
    secondaryMuscles: ['Triceps', 'Anterior Deltoid'],
    movementPattern: 'horizontal_push', exerciseType: 'compound',
    goalTags: ['strength', 'hypertrophy'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Incline DB Press',
    category: 'compound', muscleGroup: 'Chest', equipment: 'dumbbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Pectoralis Major (Upper)',
    secondaryMuscles: ['Triceps', 'Anterior Deltoid'],
    movementPattern: 'horizontal_push', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'strength'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Decline Bench Press',
    category: 'compound', muscleGroup: 'Chest', equipment: 'barbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Pectoralis Major (Lower)',
    secondaryMuscles: ['Triceps', 'Anterior Deltoid'],
    movementPattern: 'horizontal_push', exerciseType: 'compound',
    goalTags: ['strength', 'hypertrophy'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Close-Grip Bench Press',
    category: 'compound', muscleGroup: 'Triceps', equipment: 'barbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Triceps',
    secondaryMuscles: ['Pectoralis Major', 'Anterior Deltoid'],
    movementPattern: 'horizontal_push', exerciseType: 'compound',
    goalTags: ['strength', 'hypertrophy'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Weighted Push-Up',
    category: 'compound', muscleGroup: 'Chest', equipment: 'bodyweight',
    bodyPart: 'Upper Body', primaryMuscle: 'Pectoralis Major',
    secondaryMuscles: ['Triceps', 'Core', 'Anterior Deltoid'],
    movementPattern: 'horizontal_push', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'general_fitness'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Machine Chest Press',
    category: 'compound', muscleGroup: 'Chest', equipment: 'machine',
    bodyPart: 'Upper Body', primaryMuscle: 'Pectoralis Major',
    secondaryMuscles: ['Triceps', 'Anterior Deltoid'],
    movementPattern: 'horizontal_push', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'general_fitness'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Smith Machine Bench Press',
    category: 'compound', muscleGroup: 'Chest', equipment: 'machine',
    bodyPart: 'Upper Body', primaryMuscle: 'Pectoralis Major',
    secondaryMuscles: ['Triceps', 'Anterior Deltoid'],
    movementPattern: 'horizontal_push', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'general_fitness'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Floor Press',
    category: 'compound', muscleGroup: 'Chest', equipment: 'barbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Pectoralis Major',
    secondaryMuscles: ['Triceps'],
    movementPattern: 'horizontal_push', exerciseType: 'compound',
    goalTags: ['strength'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Cable Chest Press',
    category: 'compound', muscleGroup: 'Chest', equipment: 'cable',
    bodyPart: 'Upper Body', primaryMuscle: 'Pectoralis Major',
    secondaryMuscles: ['Triceps', 'Anterior Deltoid'],
    movementPattern: 'horizontal_push', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'general_fitness'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Fly Machine',
    category: 'isolation', muscleGroup: 'Chest', equipment: 'machine',
    bodyPart: 'Upper Body', primaryMuscle: 'Pectoralis Major',
    secondaryMuscles: ['Anterior Deltoid'],
    movementPattern: 'horizontal_push', exerciseType: 'isolation',
    goalTags: ['hypertrophy'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Cable Fly',
    category: 'isolation', muscleGroup: 'Chest', equipment: 'cable',
    bodyPart: 'Upper Body', primaryMuscle: 'Pectoralis Major',
    secondaryMuscles: ['Anterior Deltoid'],
    movementPattern: 'horizontal_push', exerciseType: 'isolation',
    goalTags: ['hypertrophy'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Dumbbell Fly',
    category: 'isolation', muscleGroup: 'Chest', equipment: 'dumbbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Pectoralis Major',
    secondaryMuscles: ['Anterior Deltoid'],
    movementPattern: 'horizontal_push', exerciseType: 'isolation',
    goalTags: ['hypertrophy'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Deficit Push-Up',
    category: 'compound', muscleGroup: 'Chest', equipment: 'bodyweight',
    bodyPart: 'Upper Body', primaryMuscle: 'Pectoralis Major',
    secondaryMuscles: ['Triceps', 'Core'],
    movementPattern: 'horizontal_push', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'general_fitness'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
];

// ─── D. UPPER BODY — VERTICAL PUSH ────────────────────────────────────────────

const VERTICAL_PUSH_EXERCISES: ExerciseDefinition[] = [
  {
    name: 'Overhead Press',
    category: 'compound', muscleGroup: 'Shoulders', equipment: 'barbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Anterior Deltoid',
    secondaryMuscles: ['Lateral Deltoid', 'Triceps', 'Core'],
    movementPattern: 'vertical_push', exerciseType: 'compound',
    goalTags: ['strength', 'hypertrophy'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
  {
    name: 'DB Shoulder Press',
    category: 'compound', muscleGroup: 'Shoulders', equipment: 'dumbbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Anterior Deltoid',
    secondaryMuscles: ['Lateral Deltoid', 'Triceps'],
    movementPattern: 'vertical_push', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'strength'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Seated Dumbbell Press',
    category: 'compound', muscleGroup: 'Shoulders', equipment: 'dumbbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Anterior Deltoid',
    secondaryMuscles: ['Lateral Deltoid', 'Triceps'],
    movementPattern: 'vertical_push', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'strength'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Push Press',
    category: 'compound', muscleGroup: 'Shoulders', equipment: 'barbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Anterior Deltoid',
    secondaryMuscles: ['Triceps', 'Quadriceps', 'Core'],
    movementPattern: 'vertical_push', exerciseType: 'compound',
    goalTags: ['strength', 'athletic_performance'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Arnold Press',
    category: 'compound', muscleGroup: 'Shoulders', equipment: 'dumbbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Deltoid',
    secondaryMuscles: ['Triceps', 'Rotator Cuff'],
    movementPattern: 'vertical_push', exerciseType: 'compound',
    goalTags: ['hypertrophy'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Machine Shoulder Press',
    category: 'compound', muscleGroup: 'Shoulders', equipment: 'machine',
    bodyPart: 'Upper Body', primaryMuscle: 'Anterior Deltoid',
    secondaryMuscles: ['Lateral Deltoid', 'Triceps'],
    movementPattern: 'vertical_push', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'general_fitness'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Landmine Press',
    category: 'compound', muscleGroup: 'Shoulders', equipment: 'barbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Anterior Deltoid',
    secondaryMuscles: ['Pectoralis Major', 'Triceps', 'Core'],
    movementPattern: 'vertical_push', exerciseType: 'compound',
    goalTags: ['strength', 'athletic_performance'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Handstand Push-Up',
    category: 'compound', muscleGroup: 'Shoulders', equipment: 'bodyweight',
    bodyPart: 'Upper Body', primaryMuscle: 'Anterior Deltoid',
    secondaryMuscles: ['Triceps', 'Trapezius', 'Core'],
    movementPattern: 'vertical_push', exerciseType: 'compound',
    goalTags: ['strength', 'athletic_performance'],
    difficulty: 'advanced', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Pike Push-Up',
    category: 'compound', muscleGroup: 'Shoulders', equipment: 'bodyweight',
    bodyPart: 'Upper Body', primaryMuscle: 'Anterior Deltoid',
    secondaryMuscles: ['Triceps', 'Core'],
    movementPattern: 'vertical_push', exerciseType: 'compound',
    goalTags: ['strength', 'general_fitness'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Lateral Raise',
    category: 'isolation', muscleGroup: 'Shoulders', equipment: 'dumbbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Lateral Deltoid',
    secondaryMuscles: [],
    movementPattern: 'vertical_push', exerciseType: 'isolation',
    goalTags: ['hypertrophy'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Front Raise',
    category: 'isolation', muscleGroup: 'Shoulders', equipment: 'dumbbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Anterior Deltoid',
    secondaryMuscles: [],
    movementPattern: 'vertical_push', exerciseType: 'isolation',
    goalTags: ['hypertrophy'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Rear Delt Raise',
    category: 'isolation', muscleGroup: 'Shoulders', equipment: 'dumbbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Posterior Deltoid',
    secondaryMuscles: ['Rhomboids', 'Trapezius'],
    movementPattern: 'vertical_push', exerciseType: 'isolation',
    goalTags: ['hypertrophy'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Upright Row',
    category: 'compound', muscleGroup: 'Shoulders', equipment: 'barbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Lateral Deltoid',
    secondaryMuscles: ['Trapezius', 'Biceps'],
    movementPattern: 'vertical_pull', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'strength'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
];

// ─── E. UPPER BODY — HORIZONTAL PULL ──────────────────────────────────────────

const HORIZONTAL_PULL_EXERCISES: ExerciseDefinition[] = [
  {
    name: 'Barbell Row',
    category: 'compound', muscleGroup: 'Back', equipment: 'barbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Latissimus Dorsi',
    secondaryMuscles: ['Rhomboids', 'Trapezius', 'Biceps', 'Erector Spinae'],
    movementPattern: 'horizontal_pull', exerciseType: 'compound',
    goalTags: ['strength', 'hypertrophy'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Pendlay Row',
    category: 'compound', muscleGroup: 'Back', equipment: 'barbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Latissimus Dorsi',
    secondaryMuscles: ['Rhomboids', 'Trapezius', 'Biceps'],
    movementPattern: 'horizontal_pull', exerciseType: 'compound',
    goalTags: ['strength', 'hypertrophy'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Dumbbell Row',
    category: 'compound', muscleGroup: 'Back', equipment: 'dumbbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Latissimus Dorsi',
    secondaryMuscles: ['Rhomboids', 'Trapezius', 'Biceps'],
    movementPattern: 'horizontal_pull', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'strength'],
    difficulty: 'beginner', isCompound: true, isUnilateral: true,
  },
  {
    name: 'Chest-Supported Row',
    category: 'compound', muscleGroup: 'Back', equipment: 'dumbbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Rhomboids',
    secondaryMuscles: ['Latissimus Dorsi', 'Trapezius', 'Biceps'],
    movementPattern: 'horizontal_pull', exerciseType: 'compound',
    goalTags: ['hypertrophy'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
  {
    name: 'T-Bar Row',
    category: 'compound', muscleGroup: 'Back', equipment: 'barbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Latissimus Dorsi',
    secondaryMuscles: ['Rhomboids', 'Trapezius', 'Biceps'],
    movementPattern: 'horizontal_pull', exerciseType: 'compound',
    goalTags: ['strength', 'hypertrophy'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Cable Row',
    category: 'isolation', muscleGroup: 'Back', equipment: 'cable',
    bodyPart: 'Upper Body', primaryMuscle: 'Latissimus Dorsi',
    secondaryMuscles: ['Rhomboids', 'Biceps'],
    movementPattern: 'horizontal_pull', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'general_fitness'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Seated Machine Row',
    category: 'compound', muscleGroup: 'Back', equipment: 'machine',
    bodyPart: 'Upper Body', primaryMuscle: 'Latissimus Dorsi',
    secondaryMuscles: ['Rhomboids', 'Biceps'],
    movementPattern: 'horizontal_pull', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'general_fitness'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Inverted Row',
    category: 'compound', muscleGroup: 'Back', equipment: 'bodyweight',
    bodyPart: 'Upper Body', primaryMuscle: 'Latissimus Dorsi',
    secondaryMuscles: ['Rhomboids', 'Biceps', 'Core'],
    movementPattern: 'horizontal_pull', exerciseType: 'compound',
    goalTags: ['strength', 'general_fitness'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Meadows Row',
    category: 'compound', muscleGroup: 'Back', equipment: 'barbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Latissimus Dorsi',
    secondaryMuscles: ['Teres Major', 'Biceps'],
    movementPattern: 'horizontal_pull', exerciseType: 'compound',
    goalTags: ['hypertrophy'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: true,
  },
  {
    name: 'Rear Delt Row',
    category: 'isolation', muscleGroup: 'Shoulders', equipment: 'dumbbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Posterior Deltoid',
    secondaryMuscles: ['Rhomboids', 'Trapezius'],
    movementPattern: 'horizontal_pull', exerciseType: 'isolation',
    goalTags: ['hypertrophy'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Face Pull',
    category: 'isolation', muscleGroup: 'Shoulders', equipment: 'cable',
    bodyPart: 'Upper Body', primaryMuscle: 'Posterior Deltoid',
    secondaryMuscles: ['Rhomboids', 'External Rotators'],
    movementPattern: 'horizontal_pull', exerciseType: 'isolation',
    goalTags: ['hypertrophy', 'mobility_recovery'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Seal Row',
    category: 'compound', muscleGroup: 'Back', equipment: 'barbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Latissimus Dorsi',
    secondaryMuscles: ['Rhomboids', 'Trapezius', 'Biceps'],
    movementPattern: 'horizontal_pull', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'strength'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
];

// ─── F. UPPER BODY — VERTICAL PULL ────────────────────────────────────────────

const VERTICAL_PULL_EXERCISES: ExerciseDefinition[] = [
  {
    name: 'Weighted Pull-ups',
    category: 'compound', muscleGroup: 'Back', equipment: 'bodyweight',
    bodyPart: 'Upper Body', primaryMuscle: 'Latissimus Dorsi',
    secondaryMuscles: ['Biceps', 'Rhomboids', 'Core'],
    movementPattern: 'vertical_pull', exerciseType: 'compound',
    goalTags: ['strength', 'hypertrophy'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Chin-Up',
    category: 'compound', muscleGroup: 'Back', equipment: 'bodyweight',
    bodyPart: 'Upper Body', primaryMuscle: 'Latissimus Dorsi',
    secondaryMuscles: ['Biceps', 'Core'],
    movementPattern: 'vertical_pull', exerciseType: 'compound',
    goalTags: ['strength', 'hypertrophy'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Neutral-Grip Pull-Up',
    category: 'compound', muscleGroup: 'Back', equipment: 'bodyweight',
    bodyPart: 'Upper Body', primaryMuscle: 'Latissimus Dorsi',
    secondaryMuscles: ['Biceps', 'Brachialis'],
    movementPattern: 'vertical_pull', exerciseType: 'compound',
    goalTags: ['strength', 'hypertrophy'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Lat Pulldown',
    category: 'compound', muscleGroup: 'Back', equipment: 'cable',
    bodyPart: 'Upper Body', primaryMuscle: 'Latissimus Dorsi',
    secondaryMuscles: ['Biceps', 'Rhomboids'],
    movementPattern: 'vertical_pull', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'strength'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Close-Grip Lat Pulldown',
    category: 'compound', muscleGroup: 'Back', equipment: 'cable',
    bodyPart: 'Upper Body', primaryMuscle: 'Latissimus Dorsi',
    secondaryMuscles: ['Biceps', 'Teres Major'],
    movementPattern: 'vertical_pull', exerciseType: 'compound',
    goalTags: ['hypertrophy'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Straight-Arm Pulldown',
    category: 'isolation', muscleGroup: 'Back', equipment: 'cable',
    bodyPart: 'Upper Body', primaryMuscle: 'Latissimus Dorsi',
    secondaryMuscles: ['Teres Major'],
    movementPattern: 'vertical_pull', exerciseType: 'isolation',
    goalTags: ['hypertrophy'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Assisted Pull-Up',
    category: 'compound', muscleGroup: 'Back', equipment: 'machine',
    bodyPart: 'Upper Body', primaryMuscle: 'Latissimus Dorsi',
    secondaryMuscles: ['Biceps', 'Core'],
    movementPattern: 'vertical_pull', exerciseType: 'compound',
    goalTags: ['strength', 'general_fitness'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Rope Pulldown',
    category: 'isolation', muscleGroup: 'Back', equipment: 'cable',
    bodyPart: 'Upper Body', primaryMuscle: 'Latissimus Dorsi',
    secondaryMuscles: [],
    movementPattern: 'vertical_pull', exerciseType: 'isolation',
    goalTags: ['hypertrophy'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Scapular Pull-Up',
    category: 'isolation', muscleGroup: 'Back', equipment: 'bodyweight',
    bodyPart: 'Upper Body', primaryMuscle: 'Trapezius (Lower)',
    secondaryMuscles: ['Rhomboids', 'Serratus Anterior'],
    movementPattern: 'vertical_pull', exerciseType: 'isolation',
    goalTags: ['mobility_recovery', 'general_fitness'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
];

// ─── G. ARMS / ACCESSORY ISOLATION ────────────────────────────────────────────

const ARMS_EXERCISES: ExerciseDefinition[] = [
  {
    name: 'Barbell Curl',
    category: 'isolation', muscleGroup: 'Biceps', equipment: 'barbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Biceps Brachii',
    secondaryMuscles: ['Brachialis', 'Brachioradialis'],
    movementPattern: 'vertical_pull', exerciseType: 'isolation',
    goalTags: ['hypertrophy'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'EZ-Bar Curl',
    category: 'isolation', muscleGroup: 'Biceps', equipment: 'barbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Biceps Brachii',
    secondaryMuscles: ['Brachialis'],
    movementPattern: 'vertical_pull', exerciseType: 'isolation',
    goalTags: ['hypertrophy'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Dumbbell Curl',
    category: 'isolation', muscleGroup: 'Biceps', equipment: 'dumbbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Biceps Brachii',
    secondaryMuscles: ['Brachialis'],
    movementPattern: 'vertical_pull', exerciseType: 'isolation',
    goalTags: ['hypertrophy'],
    difficulty: 'beginner', isCompound: false, isUnilateral: true,
  },
  {
    name: 'Hammer Curl',
    category: 'isolation', muscleGroup: 'Biceps', equipment: 'dumbbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Brachialis',
    secondaryMuscles: ['Biceps Brachii', 'Brachioradialis'],
    movementPattern: 'vertical_pull', exerciseType: 'isolation',
    goalTags: ['hypertrophy'],
    difficulty: 'beginner', isCompound: false, isUnilateral: true,
  },
  {
    name: 'Incline Curl',
    category: 'isolation', muscleGroup: 'Biceps', equipment: 'dumbbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Biceps Brachii (Long Head)',
    secondaryMuscles: ['Brachialis'],
    movementPattern: 'vertical_pull', exerciseType: 'isolation',
    goalTags: ['hypertrophy'],
    difficulty: 'beginner', isCompound: false, isUnilateral: true,
  },
  {
    name: 'Preacher Curl',
    category: 'isolation', muscleGroup: 'Biceps', equipment: 'barbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Biceps Brachii (Short Head)',
    secondaryMuscles: ['Brachialis'],
    movementPattern: 'vertical_pull', exerciseType: 'isolation',
    goalTags: ['hypertrophy'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Cable Curl',
    category: 'isolation', muscleGroup: 'Biceps', equipment: 'cable',
    bodyPart: 'Upper Body', primaryMuscle: 'Biceps Brachii',
    secondaryMuscles: [],
    movementPattern: 'vertical_pull', exerciseType: 'isolation',
    goalTags: ['hypertrophy'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Concentration Curl',
    category: 'isolation', muscleGroup: 'Biceps', equipment: 'dumbbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Biceps Brachii',
    secondaryMuscles: [],
    movementPattern: 'vertical_pull', exerciseType: 'isolation',
    goalTags: ['hypertrophy'],
    difficulty: 'beginner', isCompound: false, isUnilateral: true,
  },
  {
    name: 'Skull Crusher',
    category: 'isolation', muscleGroup: 'Triceps', equipment: 'barbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Triceps Brachii',
    secondaryMuscles: [],
    movementPattern: 'horizontal_push', exerciseType: 'isolation',
    goalTags: ['hypertrophy', 'strength'],
    difficulty: 'intermediate', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Triceps Pushdown',
    category: 'isolation', muscleGroup: 'Triceps', equipment: 'cable',
    bodyPart: 'Upper Body', primaryMuscle: 'Triceps Brachii',
    secondaryMuscles: [],
    movementPattern: 'vertical_push', exerciseType: 'isolation',
    goalTags: ['hypertrophy'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Overhead Triceps Extension',
    category: 'isolation', muscleGroup: 'Triceps', equipment: 'dumbbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Triceps Brachii (Long Head)',
    secondaryMuscles: [],
    movementPattern: 'vertical_push', exerciseType: 'isolation',
    goalTags: ['hypertrophy'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Rope Pushdown',
    category: 'isolation', muscleGroup: 'Triceps', equipment: 'cable',
    bodyPart: 'Upper Body', primaryMuscle: 'Triceps Brachii',
    secondaryMuscles: [],
    movementPattern: 'vertical_push', exerciseType: 'isolation',
    goalTags: ['hypertrophy'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Bench Dip',
    category: 'compound', muscleGroup: 'Triceps', equipment: 'bodyweight',
    bodyPart: 'Upper Body', primaryMuscle: 'Triceps Brachii',
    secondaryMuscles: ['Anterior Deltoid', 'Pectoralis Major'],
    movementPattern: 'horizontal_push', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'general_fitness'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
  {
    name: 'JM Press',
    category: 'compound', muscleGroup: 'Triceps', equipment: 'barbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Triceps Brachii',
    secondaryMuscles: ['Pectoralis Major'],
    movementPattern: 'horizontal_push', exerciseType: 'compound',
    goalTags: ['strength', 'hypertrophy'],
    difficulty: 'advanced', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Wrist Curl',
    category: 'isolation', muscleGroup: 'Forearms', equipment: 'barbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Forearm Flexors',
    secondaryMuscles: [],
    movementPattern: 'rotation', exerciseType: 'isolation',
    goalTags: ['hypertrophy', 'general_fitness'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Reverse Curl',
    category: 'isolation', muscleGroup: 'Forearms', equipment: 'barbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Brachioradialis',
    secondaryMuscles: ['Forearm Extensors'],
    movementPattern: 'vertical_pull', exerciseType: 'isolation',
    goalTags: ['hypertrophy'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
];

// ─── H. GLUTE-SPECIFIC / ABDUCTION-ADDUCTION ──────────────────────────────────

const GLUTE_EXERCISES: ExerciseDefinition[] = [
  {
    name: 'Hip Abduction Machine',
    category: 'isolation', muscleGroup: 'Glutes', equipment: 'machine',
    bodyPart: 'Lower Body', primaryMuscle: 'Gluteus Medius',
    secondaryMuscles: ['TFL'],
    movementPattern: 'lunge_single_leg', exerciseType: 'isolation',
    goalTags: ['hypertrophy', 'general_fitness'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Hip Adduction Machine',
    category: 'isolation', muscleGroup: 'Adductors', equipment: 'machine',
    bodyPart: 'Lower Body', primaryMuscle: 'Adductors',
    secondaryMuscles: [],
    movementPattern: 'lunge_single_leg', exerciseType: 'isolation',
    goalTags: ['hypertrophy', 'general_fitness'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Cable Kickback',
    category: 'isolation', muscleGroup: 'Glutes', equipment: 'cable',
    bodyPart: 'Lower Body', primaryMuscle: 'Gluteus Maximus',
    secondaryMuscles: ['Hamstrings'],
    movementPattern: 'hinge', exerciseType: 'isolation',
    goalTags: ['hypertrophy'],
    difficulty: 'beginner', isCompound: false, isUnilateral: true,
  },
  {
    name: 'Frog Pump',
    category: 'isolation', muscleGroup: 'Glutes', equipment: 'bodyweight',
    bodyPart: 'Lower Body', primaryMuscle: 'Gluteus Maximus',
    secondaryMuscles: [],
    movementPattern: 'hinge', exerciseType: 'isolation',
    goalTags: ['hypertrophy', 'mobility_recovery'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Banded Lateral Walk',
    category: 'isolation', muscleGroup: 'Glutes', equipment: 'band',
    bodyPart: 'Lower Body', primaryMuscle: 'Gluteus Medius',
    secondaryMuscles: ['TFL'],
    movementPattern: 'balance', exerciseType: 'rehab',
    goalTags: ['mobility_recovery', 'general_fitness'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Clamshell',
    category: 'isolation', muscleGroup: 'Glutes', equipment: 'band',
    bodyPart: 'Lower Body', primaryMuscle: 'Gluteus Medius',
    secondaryMuscles: ['External Rotators'],
    movementPattern: 'balance', exerciseType: 'rehab',
    goalTags: ['mobility_recovery', 'general_fitness'],
    difficulty: 'beginner', isCompound: false, isUnilateral: true,
  },
  {
    name: 'Copenhagen Plank',
    category: 'core', muscleGroup: 'Adductors', equipment: 'bodyweight',
    bodyPart: 'Core', primaryMuscle: 'Adductors',
    secondaryMuscles: ['Core', 'Hip Flexors'],
    movementPattern: 'anti_rotation', exerciseType: 'core',
    goalTags: ['strength', 'mobility_recovery'],
    difficulty: 'intermediate', isCompound: false, isUnilateral: true,
  },
  {
    name: 'Single-Leg Glute Bridge',
    category: 'compound', muscleGroup: 'Glutes', equipment: 'bodyweight',
    bodyPart: 'Lower Body', primaryMuscle: 'Gluteus Maximus',
    secondaryMuscles: ['Hamstrings', 'Core'],
    movementPattern: 'hinge', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'general_fitness', 'mobility_recovery'],
    difficulty: 'beginner', isCompound: true, isUnilateral: true,
  },
];

// ─── I. CORE — FLEXION / STABILITY / ANTI-ROTATION / CARRY ───────────────────

const CORE_EXERCISES: ExerciseDefinition[] = [
  {
    name: 'Plank',
    category: 'core', muscleGroup: 'Core', equipment: 'bodyweight',
    bodyPart: 'Core', primaryMuscle: 'Core',
    secondaryMuscles: ['Glutes', 'Shoulders'],
    movementPattern: 'anti_rotation', exerciseType: 'core',
    goalTags: ['general_fitness', 'endurance'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Side Plank',
    category: 'core', muscleGroup: 'Core', equipment: 'bodyweight',
    bodyPart: 'Core', primaryMuscle: 'Obliques',
    secondaryMuscles: ['Glutes', 'Core'],
    movementPattern: 'anti_rotation', exerciseType: 'core',
    goalTags: ['general_fitness', 'endurance'],
    difficulty: 'beginner', isCompound: false, isUnilateral: true,
  },
  {
    name: 'Dead Bug',
    category: 'core', muscleGroup: 'Core', equipment: 'bodyweight',
    bodyPart: 'Core', primaryMuscle: 'Core',
    secondaryMuscles: ['Hip Flexors'],
    movementPattern: 'anti_rotation', exerciseType: 'core',
    goalTags: ['general_fitness', 'mobility_recovery'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Bird Dog',
    category: 'core', muscleGroup: 'Core', equipment: 'bodyweight',
    bodyPart: 'Core', primaryMuscle: 'Core',
    secondaryMuscles: ['Glutes', 'Erector Spinae'],
    movementPattern: 'anti_rotation', exerciseType: 'core',
    goalTags: ['general_fitness', 'mobility_recovery'],
    difficulty: 'beginner', isCompound: false, isUnilateral: true,
  },
  {
    name: 'Hollow Body Hold',
    category: 'core', muscleGroup: 'Core', equipment: 'bodyweight',
    bodyPart: 'Core', primaryMuscle: 'Core',
    secondaryMuscles: ['Hip Flexors'],
    movementPattern: 'anti_rotation', exerciseType: 'core',
    goalTags: ['strength', 'athletic_performance'],
    difficulty: 'intermediate', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Ab Wheel Rollout',
    category: 'core', muscleGroup: 'Core', equipment: 'mixed',
    bodyPart: 'Core', primaryMuscle: 'Core',
    secondaryMuscles: ['Shoulders', 'Lats'],
    movementPattern: 'anti_rotation', exerciseType: 'core',
    goalTags: ['strength', 'hypertrophy'],
    difficulty: 'intermediate', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Hanging Leg Raise',
    category: 'core', muscleGroup: 'Core', equipment: 'bodyweight',
    bodyPart: 'Core', primaryMuscle: 'Hip Flexors',
    secondaryMuscles: ['Core', 'Rectus Abdominis'],
    movementPattern: 'rotation', exerciseType: 'core',
    goalTags: ['strength', 'hypertrophy'],
    difficulty: 'intermediate', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Cable Crunch',
    category: 'isolation', muscleGroup: 'Core', equipment: 'cable',
    bodyPart: 'Core', primaryMuscle: 'Rectus Abdominis',
    secondaryMuscles: [],
    movementPattern: 'rotation', exerciseType: 'core',
    goalTags: ['hypertrophy'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Reverse Crunch',
    category: 'core', muscleGroup: 'Core', equipment: 'bodyweight',
    bodyPart: 'Core', primaryMuscle: 'Rectus Abdominis (Lower)',
    secondaryMuscles: ['Hip Flexors'],
    movementPattern: 'rotation', exerciseType: 'core',
    goalTags: ['hypertrophy', 'general_fitness'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Pallof Press',
    category: 'core', muscleGroup: 'Core', equipment: 'cable',
    bodyPart: 'Core', primaryMuscle: 'Obliques',
    secondaryMuscles: ['Core', 'Shoulders'],
    movementPattern: 'anti_rotation', exerciseType: 'core',
    goalTags: ['strength', 'athletic_performance'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Russian Twist',
    category: 'core', muscleGroup: 'Core', equipment: 'bodyweight',
    bodyPart: 'Core', primaryMuscle: 'Obliques',
    secondaryMuscles: ['Rectus Abdominis'],
    movementPattern: 'rotation', exerciseType: 'core',
    goalTags: ['hypertrophy', 'athletic_performance'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Medicine Ball Rotational Throw',
    category: 'compound', muscleGroup: 'Core', equipment: 'mixed',
    bodyPart: 'Core', primaryMuscle: 'Obliques',
    secondaryMuscles: ['Core', 'Shoulders', 'Hips'],
    movementPattern: 'rotation', exerciseType: 'plyometric',
    goalTags: ['athletic_performance', 'fat_loss'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Suitcase Carry',
    category: 'core', muscleGroup: 'Core', equipment: 'dumbbell',
    bodyPart: 'Core', primaryMuscle: 'Obliques',
    secondaryMuscles: ['Core', 'Forearms', 'Trapezius'],
    movementPattern: 'carry', exerciseType: 'core',
    goalTags: ['strength', 'athletic_performance'],
    difficulty: 'beginner', isCompound: false, isUnilateral: true,
  },
  {
    name: 'Farmer Carry',
    category: 'compound', muscleGroup: 'Full Body', equipment: 'dumbbell',
    bodyPart: 'Full Body', primaryMuscle: 'Core',
    secondaryMuscles: ['Trapezius', 'Forearms', 'Legs'],
    movementPattern: 'carry', exerciseType: 'compound',
    goalTags: ['strength', 'athletic_performance', 'fat_loss'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Overhead Carry',
    category: 'compound', muscleGroup: 'Core', equipment: 'dumbbell',
    bodyPart: 'Full Body', primaryMuscle: 'Core',
    secondaryMuscles: ['Shoulders', 'Trapezius'],
    movementPattern: 'carry', exerciseType: 'compound',
    goalTags: ['strength', 'athletic_performance'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Stir the Pot',
    category: 'core', muscleGroup: 'Core', equipment: 'mixed',
    bodyPart: 'Core', primaryMuscle: 'Core',
    secondaryMuscles: ['Shoulders'],
    movementPattern: 'anti_rotation', exerciseType: 'core',
    goalTags: ['strength', 'general_fitness'],
    difficulty: 'intermediate', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Mountain Climber',
    category: 'cardio', muscleGroup: 'Core', equipment: 'bodyweight',
    bodyPart: 'Core', primaryMuscle: 'Core',
    secondaryMuscles: ['Shoulders', 'Hip Flexors'],
    movementPattern: 'cardio', exerciseType: 'cardio',
    goalTags: ['fat_loss', 'endurance', 'general_fitness'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
];

// ─── J. POWER / PLYOMETRIC / SPEED ────────────────────────────────────────────

const POWER_EXERCISES: ExerciseDefinition[] = [
  {
    name: 'Box Jump',
    category: 'compound', muscleGroup: 'Full Body', equipment: 'bodyweight',
    bodyPart: 'Lower Body', primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Calves', 'Core'],
    movementPattern: 'squat', exerciseType: 'plyometric',
    goalTags: ['athletic_performance', 'fat_loss'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Broad Jump',
    category: 'compound', muscleGroup: 'Full Body', equipment: 'bodyweight',
    bodyPart: 'Lower Body', primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Calves'],
    movementPattern: 'hinge', exerciseType: 'plyometric',
    goalTags: ['athletic_performance'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Depth Jump',
    category: 'compound', muscleGroup: 'Full Body', equipment: 'bodyweight',
    bodyPart: 'Lower Body', primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Calves'],
    movementPattern: 'squat', exerciseType: 'plyometric',
    goalTags: ['athletic_performance'],
    difficulty: 'advanced', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Jump Squat',
    category: 'compound', muscleGroup: 'Full Body', equipment: 'bodyweight',
    bodyPart: 'Lower Body', primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Calves', 'Core'],
    movementPattern: 'squat', exerciseType: 'plyometric',
    goalTags: ['athletic_performance', 'fat_loss'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Medicine Ball Slam',
    category: 'compound', muscleGroup: 'Full Body', equipment: 'mixed',
    bodyPart: 'Full Body', primaryMuscle: 'Core',
    secondaryMuscles: ['Shoulders', 'Lats', 'Hips'],
    movementPattern: 'rotation', exerciseType: 'plyometric',
    goalTags: ['athletic_performance', 'fat_loss'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Medicine Ball Chest Pass',
    category: 'compound', muscleGroup: 'Chest', equipment: 'mixed',
    bodyPart: 'Upper Body', primaryMuscle: 'Pectoralis Major',
    secondaryMuscles: ['Triceps', 'Anterior Deltoid'],
    movementPattern: 'horizontal_push', exerciseType: 'plyometric',
    goalTags: ['athletic_performance'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Power Clean',
    category: 'compound', muscleGroup: 'Full Body', equipment: 'barbell',
    bodyPart: 'Full Body', primaryMuscle: 'Trapezius',
    secondaryMuscles: ['Glutes', 'Hamstrings', 'Quadriceps', 'Shoulders'],
    movementPattern: 'hinge', exerciseType: 'plyometric',
    goalTags: ['strength', 'athletic_performance'],
    difficulty: 'advanced', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Hang Clean',
    category: 'compound', muscleGroup: 'Full Body', equipment: 'barbell',
    bodyPart: 'Full Body', primaryMuscle: 'Trapezius',
    secondaryMuscles: ['Glutes', 'Hamstrings', 'Shoulders'],
    movementPattern: 'hinge', exerciseType: 'plyometric',
    goalTags: ['strength', 'athletic_performance'],
    difficulty: 'advanced', isCompound: true, isUnilateral: false,
  },
  {
    name: 'High Pull',
    category: 'compound', muscleGroup: 'Full Body', equipment: 'barbell',
    bodyPart: 'Full Body', primaryMuscle: 'Trapezius',
    secondaryMuscles: ['Shoulders', 'Glutes', 'Hamstrings'],
    movementPattern: 'hinge', exerciseType: 'plyometric',
    goalTags: ['athletic_performance', 'strength'],
    difficulty: 'advanced', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Sprint',
    category: 'cardio', muscleGroup: 'Full Body', equipment: null,
    bodyPart: 'Cardio', primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Hamstrings', 'Glutes', 'Calves'],
    movementPattern: 'cardio', exerciseType: 'cardio',
    goalTags: ['athletic_performance', 'fat_loss', 'endurance'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Sled Push',
    category: 'compound', muscleGroup: 'Full Body', equipment: 'mixed',
    bodyPart: 'Full Body', primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Core', 'Calves'],
    movementPattern: 'cardio', exerciseType: 'compound',
    goalTags: ['athletic_performance', 'fat_loss', 'strength'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Sled Pull',
    category: 'compound', muscleGroup: 'Full Body', equipment: 'mixed',
    bodyPart: 'Full Body', primaryMuscle: 'Hamstrings',
    secondaryMuscles: ['Glutes', 'Back', 'Core'],
    movementPattern: 'cardio', exerciseType: 'compound',
    goalTags: ['athletic_performance', 'fat_loss', 'strength'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Battle Rope Slams',
    category: 'cardio', muscleGroup: 'Full Body', equipment: 'mixed',
    bodyPart: 'Full Body', primaryMuscle: 'Shoulders',
    secondaryMuscles: ['Core', 'Forearms'],
    movementPattern: 'cardio', exerciseType: 'cardio',
    goalTags: ['fat_loss', 'endurance', 'athletic_performance'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
];

// ─── K. CARDIO / CONDITIONING ──────────────────────────────────────────────────

const CARDIO_EXERCISES: ExerciseDefinition[] = [
  {
    name: 'Incline Walk',
    category: 'cardio', muscleGroup: null, equipment: 'cardio_machine',
    bodyPart: 'Cardio', primaryMuscle: 'Cardiovascular System',
    secondaryMuscles: ['Glutes', 'Calves'],
    movementPattern: 'cardio', exerciseType: 'cardio',
    goalTags: ['fat_loss', 'endurance', 'general_fitness'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Treadmill Run',
    category: 'cardio', muscleGroup: null, equipment: 'cardio_machine',
    bodyPart: 'Cardio', primaryMuscle: 'Cardiovascular System',
    secondaryMuscles: ['Quadriceps', 'Hamstrings', 'Calves'],
    movementPattern: 'cardio', exerciseType: 'cardio',
    goalTags: ['endurance', 'fat_loss', 'general_fitness'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Outdoor Run',
    category: 'cardio', muscleGroup: null, equipment: null,
    bodyPart: 'Cardio', primaryMuscle: 'Cardiovascular System',
    secondaryMuscles: ['Quadriceps', 'Hamstrings', 'Calves'],
    movementPattern: 'cardio', exerciseType: 'cardio',
    goalTags: ['endurance', 'fat_loss', 'general_fitness'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Bike',
    category: 'cardio', muscleGroup: null, equipment: 'cardio_machine',
    bodyPart: 'Cardio', primaryMuscle: 'Cardiovascular System',
    secondaryMuscles: ['Quadriceps', 'Glutes'],
    movementPattern: 'cardio', exerciseType: 'cardio',
    goalTags: ['endurance', 'fat_loss', 'general_fitness'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Assault Bike',
    category: 'cardio', muscleGroup: null, equipment: 'cardio_machine',
    bodyPart: 'Cardio', primaryMuscle: 'Cardiovascular System',
    secondaryMuscles: ['Upper Body', 'Lower Body'],
    movementPattern: 'cardio', exerciseType: 'cardio',
    goalTags: ['endurance', 'fat_loss', 'athletic_performance'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Rowing Machine',
    category: 'cardio', muscleGroup: null, equipment: 'cardio_machine',
    bodyPart: 'Cardio', primaryMuscle: 'Cardiovascular System',
    secondaryMuscles: ['Back', 'Legs', 'Core'],
    movementPattern: 'cardio', exerciseType: 'cardio',
    goalTags: ['endurance', 'fat_loss', 'general_fitness'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'SkiErg',
    category: 'cardio', muscleGroup: null, equipment: 'cardio_machine',
    bodyPart: 'Cardio', primaryMuscle: 'Cardiovascular System',
    secondaryMuscles: ['Core', 'Lats', 'Triceps'],
    movementPattern: 'cardio', exerciseType: 'cardio',
    goalTags: ['endurance', 'fat_loss', 'athletic_performance'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Stair Climber',
    category: 'cardio', muscleGroup: null, equipment: 'cardio_machine',
    bodyPart: 'Cardio', primaryMuscle: 'Cardiovascular System',
    secondaryMuscles: ['Glutes', 'Quadriceps', 'Calves'],
    movementPattern: 'cardio', exerciseType: 'cardio',
    goalTags: ['endurance', 'fat_loss', 'general_fitness'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Elliptical',
    category: 'cardio', muscleGroup: null, equipment: 'cardio_machine',
    bodyPart: 'Cardio', primaryMuscle: 'Cardiovascular System',
    secondaryMuscles: ['Legs', 'Core'],
    movementPattern: 'cardio', exerciseType: 'cardio',
    goalTags: ['endurance', 'fat_loss', 'general_fitness'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Jump Rope',
    category: 'cardio', muscleGroup: null, equipment: 'mixed',
    bodyPart: 'Cardio', primaryMuscle: 'Cardiovascular System',
    secondaryMuscles: ['Calves', 'Shoulders', 'Core'],
    movementPattern: 'cardio', exerciseType: 'cardio',
    goalTags: ['fat_loss', 'endurance', 'athletic_performance'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Swimming',
    category: 'cardio', muscleGroup: null, equipment: null,
    bodyPart: 'Cardio', primaryMuscle: 'Cardiovascular System',
    secondaryMuscles: ['Full Body'],
    movementPattern: 'cardio', exerciseType: 'cardio',
    goalTags: ['endurance', 'fat_loss', 'general_fitness', 'mobility_recovery'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Circuit Training',
    category: 'cardio', muscleGroup: null, equipment: null,
    bodyPart: 'Cardio', primaryMuscle: 'Cardiovascular System',
    secondaryMuscles: ['Full Body'],
    movementPattern: 'cardio', exerciseType: 'cardio',
    goalTags: ['fat_loss', 'endurance', 'general_fitness'],
    difficulty: 'intermediate', isCompound: false, isUnilateral: false,
  },
  {
    name: 'HIIT',
    category: 'cardio', muscleGroup: null, equipment: null,
    bodyPart: 'Cardio', primaryMuscle: 'Cardiovascular System',
    secondaryMuscles: ['Full Body'],
    movementPattern: 'cardio', exerciseType: 'cardio',
    goalTags: ['fat_loss', 'endurance', 'athletic_performance'],
    difficulty: 'intermediate', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Tempo Run',
    category: 'cardio', muscleGroup: null, equipment: null,
    bodyPart: 'Cardio', primaryMuscle: 'Cardiovascular System',
    secondaryMuscles: ['Quadriceps', 'Hamstrings', 'Calves'],
    movementPattern: 'cardio', exerciseType: 'cardio',
    goalTags: ['endurance', 'athletic_performance'],
    difficulty: 'intermediate', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Zone 2 Cardio',
    category: 'cardio', muscleGroup: null, equipment: null,
    bodyPart: 'Cardio', primaryMuscle: 'Cardiovascular System',
    secondaryMuscles: [],
    movementPattern: 'cardio', exerciseType: 'cardio',
    goalTags: ['endurance', 'fat_loss', 'general_fitness'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
];

// ─── L. MOBILITY / FLEXIBILITY / RECOVERY ─────────────────────────────────────

const MOBILITY_EXERCISES: ExerciseDefinition[] = [
  {
    name: 'Hamstring Stretch',
    category: 'cardio', muscleGroup: 'Hamstrings', equipment: null,
    bodyPart: 'Mobility', primaryMuscle: 'Hamstrings',
    secondaryMuscles: ['Calves'],
    movementPattern: 'mobility', exerciseType: 'mobility',
    goalTags: ['mobility_recovery'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Hip Flexor Stretch',
    category: 'cardio', muscleGroup: 'Hip Flexors', equipment: null,
    bodyPart: 'Mobility', primaryMuscle: 'Hip Flexors',
    secondaryMuscles: ['Quadriceps'],
    movementPattern: 'mobility', exerciseType: 'mobility',
    goalTags: ['mobility_recovery'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Quad Stretch',
    category: 'cardio', muscleGroup: 'Quads', equipment: null,
    bodyPart: 'Mobility', primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Hip Flexors'],
    movementPattern: 'mobility', exerciseType: 'mobility',
    goalTags: ['mobility_recovery'],
    difficulty: 'beginner', isCompound: false, isUnilateral: true,
  },
  {
    name: 'Chest Stretch',
    category: 'cardio', muscleGroup: 'Chest', equipment: null,
    bodyPart: 'Mobility', primaryMuscle: 'Pectoralis Major',
    secondaryMuscles: ['Anterior Deltoid'],
    movementPattern: 'mobility', exerciseType: 'mobility',
    goalTags: ['mobility_recovery'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Lat Stretch',
    category: 'cardio', muscleGroup: 'Back', equipment: null,
    bodyPart: 'Mobility', primaryMuscle: 'Latissimus Dorsi',
    secondaryMuscles: ['Teres Major'],
    movementPattern: 'mobility', exerciseType: 'mobility',
    goalTags: ['mobility_recovery'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Thoracic Rotation',
    category: 'cardio', muscleGroup: 'Back', equipment: null,
    bodyPart: 'Mobility', primaryMuscle: 'Thoracic Spine',
    secondaryMuscles: ['Obliques'],
    movementPattern: 'rotation', exerciseType: 'mobility',
    goalTags: ['mobility_recovery'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: '90/90 Hip Flow',
    category: 'cardio', muscleGroup: 'Hips', equipment: null,
    bodyPart: 'Mobility', primaryMuscle: 'Hip External Rotators',
    secondaryMuscles: ['Hip Flexors', 'Glutes'],
    movementPattern: 'mobility', exerciseType: 'mobility',
    goalTags: ['mobility_recovery'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: "World's Greatest Stretch",
    category: 'cardio', muscleGroup: 'Full Body', equipment: null,
    bodyPart: 'Mobility', primaryMuscle: 'Hip Flexors',
    secondaryMuscles: ['Thoracic Spine', 'Glutes', 'Hamstrings'],
    movementPattern: 'mobility', exerciseType: 'mobility',
    goalTags: ['mobility_recovery', 'general_fitness'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Cat-Cow',
    category: 'cardio', muscleGroup: 'Back', equipment: null,
    bodyPart: 'Mobility', primaryMuscle: 'Erector Spinae',
    secondaryMuscles: ['Core'],
    movementPattern: 'mobility', exerciseType: 'mobility',
    goalTags: ['mobility_recovery'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: "Child's Pose",
    category: 'cardio', muscleGroup: 'Back', equipment: null,
    bodyPart: 'Mobility', primaryMuscle: 'Lats',
    secondaryMuscles: ['Thoracic Spine', 'Hips'],
    movementPattern: 'mobility', exerciseType: 'mobility',
    goalTags: ['mobility_recovery'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Downward Dog',
    category: 'cardio', muscleGroup: 'Full Body', equipment: null,
    bodyPart: 'Mobility', primaryMuscle: 'Hamstrings',
    secondaryMuscles: ['Calves', 'Shoulders', 'Lats'],
    movementPattern: 'mobility', exerciseType: 'mobility',
    goalTags: ['mobility_recovery', 'general_fitness'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Couch Stretch',
    category: 'cardio', muscleGroup: 'Hip Flexors', equipment: null,
    bodyPart: 'Mobility', primaryMuscle: 'Hip Flexors',
    secondaryMuscles: ['Quadriceps'],
    movementPattern: 'mobility', exerciseType: 'mobility',
    goalTags: ['mobility_recovery'],
    difficulty: 'beginner', isCompound: false, isUnilateral: true,
  },
  {
    name: 'Ankle Dorsiflexion Drill',
    category: 'cardio', muscleGroup: 'Calves', equipment: null,
    bodyPart: 'Mobility', primaryMuscle: 'Soleus',
    secondaryMuscles: ['Gastrocnemius'],
    movementPattern: 'mobility', exerciseType: 'rehab',
    goalTags: ['mobility_recovery'],
    difficulty: 'beginner', isCompound: false, isUnilateral: true,
  },
  {
    name: 'Shoulder CARs',
    category: 'cardio', muscleGroup: 'Shoulders', equipment: null,
    bodyPart: 'Mobility', primaryMuscle: 'Shoulder Rotators',
    secondaryMuscles: ['Rotator Cuff'],
    movementPattern: 'rotation', exerciseType: 'mobility',
    goalTags: ['mobility_recovery'],
    difficulty: 'beginner', isCompound: false, isUnilateral: true,
  },
  {
    name: 'Hip CARs',
    category: 'cardio', muscleGroup: 'Hips', equipment: null,
    bodyPart: 'Mobility', primaryMuscle: 'Hip Flexors',
    secondaryMuscles: ['Glutes', 'Hip Rotators'],
    movementPattern: 'rotation', exerciseType: 'mobility',
    goalTags: ['mobility_recovery'],
    difficulty: 'beginner', isCompound: false, isUnilateral: true,
  },
  {
    name: 'Band Shoulder Dislocates',
    category: 'cardio', muscleGroup: 'Shoulders', equipment: 'band',
    bodyPart: 'Mobility', primaryMuscle: 'Shoulder Rotators',
    secondaryMuscles: ['Pectoralis Major', 'Lats'],
    movementPattern: 'rotation', exerciseType: 'mobility',
    goalTags: ['mobility_recovery'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Foam Rolling Quads',
    category: 'cardio', muscleGroup: 'Quads', equipment: 'mixed',
    bodyPart: 'Mobility', primaryMuscle: 'Quadriceps',
    secondaryMuscles: [],
    movementPattern: 'mobility', exerciseType: 'mobility',
    goalTags: ['mobility_recovery'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Foam Rolling Lats',
    category: 'cardio', muscleGroup: 'Back', equipment: 'mixed',
    bodyPart: 'Mobility', primaryMuscle: 'Latissimus Dorsi',
    secondaryMuscles: [],
    movementPattern: 'mobility', exerciseType: 'mobility',
    goalTags: ['mobility_recovery'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Walk + Stretch',
    category: 'cardio', muscleGroup: null, equipment: null,
    bodyPart: 'Mobility', primaryMuscle: 'Cardiovascular System',
    secondaryMuscles: ['Full Body'],
    movementPattern: 'mobility', exerciseType: 'mobility',
    goalTags: ['mobility_recovery', 'general_fitness'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
];

// ─── M. BALANCE / NEUROMOTOR / REHAB-FRIENDLY ─────────────────────────────────

const BALANCE_EXERCISES: ExerciseDefinition[] = [
  {
    name: 'Single-Leg Balance',
    category: 'core', muscleGroup: 'Full Body', equipment: 'bodyweight',
    bodyPart: 'Full Body', primaryMuscle: 'Proprioception',
    secondaryMuscles: ['Ankles', 'Core', 'Glutes'],
    movementPattern: 'balance', exerciseType: 'rehab',
    goalTags: ['mobility_recovery', 'general_fitness'],
    difficulty: 'beginner', isCompound: false, isUnilateral: true,
  },
  {
    name: 'Tandem Walk',
    category: 'core', muscleGroup: 'Full Body', equipment: 'bodyweight',
    bodyPart: 'Full Body', primaryMuscle: 'Proprioception',
    secondaryMuscles: ['Core', 'Ankles'],
    movementPattern: 'balance', exerciseType: 'rehab',
    goalTags: ['mobility_recovery', 'general_fitness'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Heel-to-Toe Walk',
    category: 'core', muscleGroup: 'Full Body', equipment: 'bodyweight',
    bodyPart: 'Full Body', primaryMuscle: 'Proprioception',
    secondaryMuscles: ['Core', 'Ankles'],
    movementPattern: 'balance', exerciseType: 'rehab',
    goalTags: ['mobility_recovery', 'general_fitness'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'BOSU Balance Hold',
    category: 'core', muscleGroup: 'Core', equipment: 'mixed',
    bodyPart: 'Core', primaryMuscle: 'Core',
    secondaryMuscles: ['Ankles', 'Glutes'],
    movementPattern: 'balance', exerciseType: 'rehab',
    goalTags: ['mobility_recovery', 'general_fitness'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Step-Over Drill',
    category: 'core', muscleGroup: 'Full Body', equipment: 'bodyweight',
    bodyPart: 'Lower Body', primaryMuscle: 'Hip Flexors',
    secondaryMuscles: ['Core', 'Glutes'],
    movementPattern: 'balance', exerciseType: 'rehab',
    goalTags: ['athletic_performance', 'mobility_recovery'],
    difficulty: 'beginner', isCompound: false, isUnilateral: true,
  },
  {
    name: 'Lateral Band Walk',
    category: 'core', muscleGroup: 'Glutes', equipment: 'band',
    bodyPart: 'Lower Body', primaryMuscle: 'Gluteus Medius',
    secondaryMuscles: ['TFL'],
    movementPattern: 'balance', exerciseType: 'rehab',
    goalTags: ['mobility_recovery', 'general_fitness'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Controlled Step-Down',
    category: 'compound', muscleGroup: 'Quads', equipment: 'bodyweight',
    bodyPart: 'Lower Body', primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Core'],
    movementPattern: 'balance', exerciseType: 'rehab',
    goalTags: ['mobility_recovery', 'general_fitness'],
    difficulty: 'beginner', isCompound: true, isUnilateral: true,
  },
  {
    name: 'Marching Carry',
    category: 'core', muscleGroup: 'Core', equipment: 'dumbbell',
    bodyPart: 'Full Body', primaryMuscle: 'Core',
    secondaryMuscles: ['Hip Flexors', 'Shoulders'],
    movementPattern: 'carry', exerciseType: 'rehab',
    goalTags: ['general_fitness', 'mobility_recovery'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Single-Leg Reach',
    category: 'core', muscleGroup: 'Full Body', equipment: 'bodyweight',
    bodyPart: 'Lower Body', primaryMuscle: 'Glutes',
    secondaryMuscles: ['Core', 'Hamstrings'],
    movementPattern: 'balance', exerciseType: 'rehab',
    goalTags: ['mobility_recovery', 'athletic_performance'],
    difficulty: 'beginner', isCompound: false, isUnilateral: true,
  },
  {
    name: 'Tempo Bodyweight Squat',
    category: 'compound', muscleGroup: 'Quads', equipment: 'bodyweight',
    bodyPart: 'Lower Body', primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Hamstrings', 'Core'],
    movementPattern: 'squat', exerciseType: 'rehab',
    goalTags: ['general_fitness', 'mobility_recovery'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
];

// ─── N. LANDMINE EXERCISES ────────────────────────────────────────────────────

const LANDMINE_EXERCISES: ExerciseDefinition[] = [
  {
    name: 'Landmine Press',
    category: 'compound', muscleGroup: 'Shoulders', equipment: 'barbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Anterior Deltoid',
    secondaryMuscles: ['Triceps', 'Core', 'Chest'],
    movementPattern: 'vertical_push', exerciseType: 'compound',
    goalTags: ['strength', 'athletic_performance'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: true,
  },
  {
    name: 'Landmine Row',
    category: 'compound', muscleGroup: 'Back', equipment: 'barbell',
    bodyPart: 'Upper Body', primaryMuscle: 'Latissimus Dorsi',
    secondaryMuscles: ['Rhomboids', 'Trapezius', 'Biceps'],
    movementPattern: 'horizontal_pull', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'strength'],
    difficulty: 'beginner', isCompound: true, isUnilateral: true,
  },
  {
    name: 'Landmine Squat',
    category: 'compound', muscleGroup: 'Quads', equipment: 'barbell',
    bodyPart: 'Lower Body', primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Hamstrings', 'Core'],
    movementPattern: 'squat', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'general_fitness'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Landmine Rotation',
    category: 'core', muscleGroup: 'Core', equipment: 'barbell',
    bodyPart: 'Core', primaryMuscle: 'Obliques',
    secondaryMuscles: ['Shoulders', 'Core'],
    movementPattern: 'anti_rotation', exerciseType: 'core',
    goalTags: ['athletic_performance', 'strength'],
    difficulty: 'intermediate', isCompound: false, isUnilateral: false,
  },
];

// ─── O. TRX / SUSPENSION EXERCISES ────────────────────────────────────────────

const TRX_EXERCISES: ExerciseDefinition[] = [
  {
    name: 'TRX Row',
    category: 'compound', muscleGroup: 'Back', equipment: 'mixed',
    bodyPart: 'Upper Body', primaryMuscle: 'Latissimus Dorsi',
    secondaryMuscles: ['Rhomboids', 'Biceps', 'Core'],
    movementPattern: 'horizontal_pull', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'general_fitness'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
  {
    name: 'TRX Push-up',
    category: 'compound', muscleGroup: 'Chest', equipment: 'mixed',
    bodyPart: 'Upper Body', primaryMuscle: 'Pectoralis Major',
    secondaryMuscles: ['Triceps', 'Anterior Deltoid', 'Core'],
    movementPattern: 'horizontal_push', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'athletic_performance'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
  {
    name: 'TRX Fallout',
    category: 'core', muscleGroup: 'Core', equipment: 'mixed',
    bodyPart: 'Core', primaryMuscle: 'Core',
    secondaryMuscles: ['Shoulders', 'Lats'],
    movementPattern: 'anti_rotation', exerciseType: 'core',
    goalTags: ['strength', 'athletic_performance'],
    difficulty: 'advanced', isCompound: false, isUnilateral: false,
  },
  {
    name: 'TRX Hamstring Curl',
    category: 'isolation', muscleGroup: 'Hamstrings', equipment: 'mixed',
    bodyPart: 'Lower Body', primaryMuscle: 'Hamstrings',
    secondaryMuscles: ['Glutes', 'Core'],
    movementPattern: 'hinge', exerciseType: 'isolation',
    goalTags: ['hypertrophy', 'athletic_performance'],
    difficulty: 'intermediate', isCompound: false, isUnilateral: false,
  },
];

// ─── P. BOSU EXERCISES ────────────────────────────────────────────────────────

const BOSU_EXERCISES: ExerciseDefinition[] = [
  {
    name: 'BOSU Squat',
    category: 'compound', muscleGroup: 'Quads', equipment: 'mixed',
    bodyPart: 'Lower Body', primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Core', 'Ankles'],
    movementPattern: 'squat', exerciseType: 'compound',
    goalTags: ['balance', 'general_fitness'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
  {
    name: 'BOSU Push-up',
    category: 'compound', muscleGroup: 'Chest', equipment: 'mixed',
    bodyPart: 'Upper Body', primaryMuscle: 'Pectoralis Major',
    secondaryMuscles: ['Triceps', 'Core'],
    movementPattern: 'horizontal_push', exerciseType: 'compound',
    goalTags: ['hypertrophy', 'balance'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
  {
    name: 'BOSU Mountain Climber',
    category: 'cardio', muscleGroup: 'Core', equipment: 'mixed',
    bodyPart: 'Full Body', primaryMuscle: 'Core',
    secondaryMuscles: ['Shoulders', 'Hip Flexors'],
    movementPattern: 'cardio', exerciseType: 'cardio',
    goalTags: ['fat_loss', 'balance'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: false,
  },
];

// ─── Q. BAND EXERCISES ────────────────────────────────────────────────────────

const BAND_EXERCISES: ExerciseDefinition[] = [
  {
    name: 'Banded Face Pull',
    category: 'isolation', muscleGroup: 'Shoulders', equipment: 'band',
    bodyPart: 'Upper Body', primaryMuscle: 'Posterior Deltoid',
    secondaryMuscles: ['Rhomboids', 'Trapezius'],
    movementPattern: 'horizontal_pull', exerciseType: 'isolation',
    goalTags: ['hypertrophy', 'mobility_recovery'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Banded Pull-apart',
    category: 'isolation', muscleGroup: 'Shoulders', equipment: 'band',
    bodyPart: 'Upper Body', primaryMuscle: 'Posterior Deltoid',
    secondaryMuscles: ['Rhomboids'],
    movementPattern: 'horizontal_pull', exerciseType: 'isolation',
    goalTags: ['mobility_recovery', 'hypertrophy'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Banded Bicep Curl',
    category: 'isolation', muscleGroup: 'Biceps', equipment: 'band',
    bodyPart: 'Upper Body', primaryMuscle: 'Biceps Brachii',
    secondaryMuscles: [],
    movementPattern: 'vertical_pull', exerciseType: 'isolation',
    goalTags: ['hypertrophy', 'general_fitness'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Banded Lateral Raise',
    category: 'isolation', muscleGroup: 'Shoulders', equipment: 'band',
    bodyPart: 'Upper Body', primaryMuscle: 'Lateral Deltoid',
    secondaryMuscles: [],
    movementPattern: 'vertical_push', exerciseType: 'isolation',
    goalTags: ['hypertrophy'],
    difficulty: 'beginner', isCompound: false, isUnilateral: false,
  },
];

// ─── R. KETTLEBELL EXERCISES ──────────────────────────────────────────────────

const KETTLEBELL_EXERCISES: ExerciseDefinition[] = [
  {
    name: 'Kettlebell Snatch',
    category: 'compound', muscleGroup: 'Full Body', equipment: 'kettlebell',
    bodyPart: 'Full Body', primaryMuscle: 'Glutes',
    secondaryMuscles: ['Hamstrings', 'Back', 'Shoulders', 'Core'],
    movementPattern: 'hinge', exerciseType: 'plyometric',
    goalTags: ['athletic_performance', 'power', 'endurance'],
    difficulty: 'advanced', isCompound: true, isUnilateral: true,
  },
  {
    name: 'Kettlebell Clean',
    category: 'compound', muscleGroup: 'Full Body', equipment: 'kettlebell',
    bodyPart: 'Full Body', primaryMuscle: 'Glutes',
    secondaryMuscles: ['Hamstrings', 'Back', 'Shoulders', 'Core'],
    movementPattern: 'hinge', exerciseType: 'compound',
    goalTags: ['athletic_performance', 'strength'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: true,
  },
  {
    name: 'Turkish Get-Up',
    category: 'compound', muscleGroup: 'Full Body', equipment: 'kettlebell',
    bodyPart: 'Full Body', primaryMuscle: 'Core',
    secondaryMuscles: ['Shoulders', 'Hips', 'Glutes', 'Back'],
    movementPattern: 'mobility', exerciseType: 'compound',
    goalTags: ['mobility_recovery', 'strength', 'athletic_performance'],
    difficulty: 'advanced', isCompound: true, isUnilateral: true,
  },
  {
    name: 'Kettlebell Windmill',
    category: 'isolation', muscleGroup: 'Core', equipment: 'kettlebell',
    bodyPart: 'Core', primaryMuscle: 'Obliques',
    secondaryMuscles: ['Shoulders', 'Hamstrings', 'Core'],
    movementPattern: 'anti_rotation', exerciseType: 'isolation',
    goalTags: ['mobility_recovery', 'hypertrophy'],
    difficulty: 'intermediate', isCompound: false, isUnilateral: true,
  },
  {
    name: 'Renegade Row',
    category: 'compound', muscleGroup: 'Back', equipment: 'kettlebell',
    bodyPart: 'Upper Body', primaryMuscle: 'Latissimus Dorsi',
    secondaryMuscles: ['Core', 'Shoulders', 'Biceps'],
    movementPattern: 'horizontal_pull', exerciseType: 'compound',
    goalTags: ['strength', 'hypertrophy', 'athletic_performance'],
    difficulty: 'intermediate', isCompound: true, isUnilateral: true,
  },
];

// ─── S. STRONGMAN EXERCISES ───────────────────────────────────────────────────

const STRONGMAN_EXERCISES: ExerciseDefinition[] = [
  {
    name: 'Atlas Stones',
    category: 'compound', muscleGroup: 'Full Body', equipment: 'mixed',
    bodyPart: 'Full Body', primaryMuscle: 'Glutes',
    secondaryMuscles: ['Hamstrings', 'Erector Spinae', 'Biceps', 'Core'],
    movementPattern: 'hinge', exerciseType: 'compound',
    goalTags: ['strength', 'athletic_performance'],
    difficulty: 'advanced', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Tire Flip',
    category: 'compound', muscleGroup: 'Full Body', equipment: 'mixed',
    bodyPart: 'Full Body', primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Hamstrings', 'Back', 'Shoulders', 'Core'],
    movementPattern: 'squat', exerciseType: 'plyometric',
    goalTags: ['strength', 'athletic_performance', 'fat_loss'],
    difficulty: 'advanced', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Log Press',
    category: 'compound', muscleGroup: 'Shoulders', equipment: 'mixed',
    bodyPart: 'Upper Body', primaryMuscle: 'Shoulders',
    secondaryMuscles: ['Triceps', 'Upper Back', 'Core'],
    movementPattern: 'vertical_push', exerciseType: 'compound',
    goalTags: ['strength', 'power'],
    difficulty: 'advanced', isCompound: true, isUnilateral: false,
  },
];

// ─── T. GYMNASTICS / BODYWEIGHT SKILLS ────────────────────────────────────────

const GYMNASTICS_EXERCISES: ExerciseDefinition[] = [
  {
    name: 'Muscle-Up',
    category: 'compound', muscleGroup: 'Full Body', equipment: 'bodyweight',
    bodyPart: 'Upper Body', primaryMuscle: 'Latissimus Dorsi',
    secondaryMuscles: ['Triceps', 'Chest', 'Shoulders', 'Biceps', 'Core'],
    movementPattern: 'vertical_pull', exerciseType: 'compound',
    goalTags: ['strength', 'athletic_performance'],
    difficulty: 'advanced', isCompound: true, isUnilateral: false,
  },
  {
    name: 'L-Sit',
    category: 'core', muscleGroup: 'Core', equipment: 'bodyweight',
    bodyPart: 'Core', primaryMuscle: 'Rectus Abdominis',
    secondaryMuscles: ['Hip Flexors', 'Triceps', 'Shoulders'],
    movementPattern: 'anti_rotation', exerciseType: 'core',
    goalTags: ['strength', 'athletic_performance'],
    difficulty: 'intermediate', isCompound: false, isUnilateral: false,
  },
  {
    name: 'Planche Push-up',
    category: 'compound', muscleGroup: 'Chest', equipment: 'bodyweight',
    bodyPart: 'Upper Body', primaryMuscle: 'Anterior Deltoid',
    secondaryMuscles: ['Chest', 'Triceps', 'Core'],
    movementPattern: 'horizontal_push', exerciseType: 'compound',
    goalTags: ['strength', 'athletic_performance'],
    difficulty: 'advanced', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Front Lever',
    category: 'compound', muscleGroup: 'Back', equipment: 'bodyweight',
    bodyPart: 'Upper Body', primaryMuscle: 'Latissimus Dorsi',
    secondaryMuscles: ['Core', 'Shoulders', 'Biceps'],
    movementPattern: 'vertical_pull', exerciseType: 'compound',
    goalTags: ['strength', 'athletic_performance'],
    difficulty: 'advanced', isCompound: true, isUnilateral: false,
  },
];

// ─── U. ANIMAL FLOW / MOVEMENT SECTIONS ───────────────────────────────────────

const ANIMAL_FLOW_EXERCISES: ExerciseDefinition[] = [
  {
    name: 'Bear Crawl',
    category: 'cardio', muscleGroup: 'Full Body', equipment: 'bodyweight',
    bodyPart: 'Full Body', primaryMuscle: 'Core',
    secondaryMuscles: ['Shoulders', 'Quadriceps', 'Hips'],
    movementPattern: 'cardio', exerciseType: 'cardio',
    goalTags: ['athletic_performance', 'fat_loss', 'mobility_recovery'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Crab Walk',
    category: 'cardio', muscleGroup: 'Full Body', equipment: 'bodyweight',
    bodyPart: 'Full Body', primaryMuscle: 'Triceps',
    secondaryMuscles: ['Glutes', 'Shoulders', 'Core'],
    movementPattern: 'cardio', exerciseType: 'cardio',
    goalTags: ['athletic_performance', 'fat_loss', 'mobility_recovery'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
  {
    name: 'Frog Jump',
    category: 'compound', muscleGroup: 'Quads', equipment: 'bodyweight',
    bodyPart: 'Lower Body', primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Calves', 'Core'],
    movementPattern: 'squat', exerciseType: 'plyometric',
    goalTags: ['athletic_performance', 'fat_loss'],
    difficulty: 'beginner', isCompound: true, isUnilateral: false,
  },
];

// ─── Full library export ───────────────────────────────────────────────────────

export const EXERCISE_LIBRARY: ExerciseDefinition[] = [
  ...SQUAT_EXERCISES,
  ...HINGE_EXERCISES,
  ...HORIZONTAL_PUSH_EXERCISES,
  ...VERTICAL_PUSH_EXERCISES,
  ...HORIZONTAL_PULL_EXERCISES,
  ...VERTICAL_PULL_EXERCISES,
  ...ARMS_EXERCISES,
  ...GLUTE_EXERCISES,
  ...CORE_EXERCISES,
  ...POWER_EXERCISES,
  ...CARDIO_EXERCISES,
  ...MOBILITY_EXERCISES,
  ...BALANCE_EXERCISES,
  ...LANDMINE_EXERCISES,
  ...TRX_EXERCISES,
  ...BOSU_EXERCISES,
  ...BAND_EXERCISES,
  ...KETTLEBELL_EXERCISES,
  ...STRONGMAN_EXERCISES,
  ...GYMNASTICS_EXERCISES,
  ...ANIMAL_FLOW_EXERCISES,
];

// ─── Substitutions ─────────────────────────────────────────────────────────────
// Format: { original: string, substitutes: string[], notes?: string }

export interface SubstitutionDef {
  original: string;
  substitutes: string[];
  notes?: string;
}

export const EXERCISE_SUBSTITUTIONS: SubstitutionDef[] = [
  // Squat
  { original: 'Back Squat', substitutes: ['Front Squat', 'Goblet Squat', 'Leg Press', 'Hack Squat'] },
  { original: 'Front Squat', substitutes: ['Back Squat', 'Goblet Squat', 'Safety Bar Squat'] },
  { original: 'Bulgarian Split Squat', substitutes: ['Split Squat', 'Reverse Lunge', 'Step-Up'] },
  // Hinge
  { original: 'Deadlift', substitutes: ['Trap Bar Deadlift', 'Romanian Deadlift', 'Rack Pull'] },
  { original: 'Romanian Deadlift', substitutes: ['Stiff-Leg Deadlift', 'Single-Leg Romanian Deadlift', 'Good Morning'] },
  { original: 'Hip Thrust', substitutes: ['Barbell Glute Bridge', 'Cable Pull-Through', 'Single-Leg Glute Bridge'] },
  // Horizontal Push
  { original: 'Bench Press', substitutes: ['Dumbbell Bench Press', 'Machine Chest Press', 'Weighted Push-Up'] },
  { original: 'Incline DB Press', substitutes: ['Incline Barbell Bench Press', 'Cable Chest Press', 'Machine Chest Press'] },
  { original: 'Close-Grip Bench Press', substitutes: ['JM Press', 'Triceps Pushdown', 'Skull Crusher'] },
  // Vertical Push
  { original: 'Overhead Press', substitutes: ['DB Shoulder Press', 'Push Press', 'Machine Shoulder Press'] },
  { original: 'DB Shoulder Press', substitutes: ['Overhead Press', 'Arnold Press', 'Machine Shoulder Press'] },
  // Horizontal Pull
  { original: 'Barbell Row', substitutes: ['Dumbbell Row', 'Cable Row', 'Seated Machine Row', 'T-Bar Row'] },
  { original: 'Cable Row', substitutes: ['Seated Machine Row', 'Dumbbell Row', 'Chest-Supported Row'] },
  // Vertical Pull
  { original: 'Weighted Pull-ups', substitutes: ['Assisted Pull-Up', 'Lat Pulldown', 'Chin-Up'] },
  { original: 'Lat Pulldown', substitutes: ['Weighted Pull-ups', 'Assisted Pull-Up', 'Close-Grip Lat Pulldown'] },
  // Isolation — Arms
  { original: 'Barbell Curl', substitutes: ['EZ-Bar Curl', 'Dumbbell Curl', 'Cable Curl'] },
  { original: 'Triceps Pushdown', substitutes: ['Rope Pushdown', 'Overhead Triceps Extension', 'Close-Grip Bench Press'] },
  { original: 'Skull Crusher', substitutes: ['JM Press', 'Triceps Pushdown', 'Overhead Triceps Extension'] },
  // Core
  { original: 'Plank', substitutes: ['Dead Bug', 'Hollow Body Hold', 'Ab Wheel Rollout'] },
  { original: 'Pallof Press', substitutes: ['Side Plank', 'Anti-Rotation Plank', 'Suitcase Carry'] },
  // Lower isolation
  { original: 'Hamstring Curl', substitutes: ['Seated Ham Curl', 'Nordic Curl', 'Single-Leg Romanian Deadlift'] },
  { original: 'Leg Extension', substitutes: ['Sissy Squat', 'Wall Sit', 'Leg Press'] },
];
